### ISSUE TITLE
Support information_schema.columns

### ISSUE THREAD

**Issue by criccomini** [tekumara/fakesnow#2]
It would be cool if `fakesnow` supported the information_schema.columns view in Snowflake, so any table that's created automatically has its columns show up there.

**Comment by tekumara** [comment]
That would be useful and feels doable!

**Comment by criccomini** [comment]
Woah, awesome! I'm going to try and integrate this tomorrow for tests in Recap. I'll close this ticket out or update with issues as I find them.
