### ISSUE TITLE
Support for `SHOW USERS`

### ISSUE THREAD

**Issue by DanCardin** [tekumara/fakesnow#43]
I wonder if it would be possible/practical to have provisional support for CRUD on roles/users? I was sort of imagining part of setup would create an `information_schema.fakesnow_users` table (since there's no information_schema table that i can see, unlike other SHOW commands that **do** have public backing tables) that matches the structure given by `SHOW USERS`.

Then `SHOW USERS` could function, even if it only returned an empty table.

But at that point, basic `CREATE/UPDATE/DELETE` `USER/ROLE` statements could probably be supported by inserting into that table.

---
If you'd support such an endeavor, I'd be interested in supplying the impl.

I believe I see that sqlglot would need to gain `SHOW USERS` syntactically. At which point I could implement up to `SHOW USERS`. Beyond that, my usecase could probably live with manually manipulating `fakesnow_users`, although certainly it'd be nice to keep going.

---

fwiw, my usecase is for adding snowflake support to https://github.com/DanCardin/sqlalchemy-declarative-extensions, wherein my usual e2e testing mechanism for the rest of the library is impractical for snowflake. Developing against a very rough approximation of users isn't ideal, but it seems better than the manual patching i would otherwise be forced to do.

**Comment by tekumara** [comment]
Yes this is very doable and, like any unimplemented feature, a welcome addition! 🙂 

If you wanted to have a go, there's some precedence for storing extra metadata per-database in `_fs_` prefixed tables, which might be a useful reference, see here: https://github.com/tekumara/fakesnow/blob/a86f238accc4d3957b684e8e96cb31153918d994/fakesnow/info_schema.py#L7 

The difference would be that a users table isn't per database but per session. So I'd suggest creating a [SNOWFLAKE database](https://docs.snowflake.com/en/sql-reference/snowflake-db) and storing the users table under a `_fs_` prefix there.

Hopefully there's enough to get started in [CONTRIBUTING.md](https://github.com/tekumara/fakesnow/blob/main/CONTRIBUTING.md). Any questions let me know and I'd be happy to help.

PS: nice use-case and library!

**Comment by tekumara** [comment]
BTW - if you only want to support `SHOW USERS` returning an empty result set, then you could do so without a table, and just transform `SHOW USERS` into a SELECT with 0 rows.

Another thing to note is that the public API of fakesnow is the Snowflake API. So if you do create a table as an internal implementation detail of providing `SHOW USERS`, then any manual manipulation of the table outside of the Snowflake API could potentially break in future versions of fakesnow without warning. The safe way would be for `CREATE USER` etc. to be implemented and used, or avoid upgrades.

**Comment by DanCardin** [comment]
for my own purposes, the plan is to implement `SHOW USERS`, so i can get my own code to react to the real empty table shape and to start issuing `CREATE USER` statements of an assumed correct output shape. And then begin to implement `CREATE USER`/`CREATE ROLE` in terms of it, once I can pass more of my own tests that start to fail due to the rest being unimplemented.

(I was at least confident in my ability to add `SHOW USERS` support to sqlglot, but I haven't even begin to look at a full/arbitrary `CREATE USER` statement, or if that'll "just work" 🤷).

I'd have a PR up already even (this bit seems **relatively** simple), except for the sqlglot update. They've merged my PR, but there's no release yet to apply this against.

---

Speaking of which, I could probably introspect sqlglot's version to check that it's at least 21.0.3 (or whatever), specifically for this feature; so that you dont have a somewhat arbitrary minimum version for what is probably a fairly niche usecase...or i can just bump the min version.

I'll probably just open a draft PR soon regardless, to have something to reference, in case i've gone off the rails.

**Comment by tekumara** [comment]
Bumping sqlglot is totally fine, I try to keep it up to date anyway. 

NB: If they release your feature as part of a major version bump there might be some backwards incompatible changes in there, which will require some fixes (here's a recent [example](https://github.com/tekumara/fakesnow/commit/e7c6c6e2b8571b047a225810571661179c5a3ec7)).

**Comment by tekumara** [comment]
Bumping sqlglot is totally fine, I try to keep it up to date anyway. 

NB: If they release your feature as part of a major version bump there might be some backwards incompatible changes in there, which will require some fixes (which I usually do as a separate PR, here's a recent [example](https://github.com/tekumara/fakesnow/commit/e7c6c6e2b8571b047a225810571661179c5a3ec7)).
