### ISSUE TITLE
Pandas dependency missing

### ISSUE THREAD

**Issue by criccomini** [tekumara/fakesnow#5]
PDM, version 2.7.4.

```
[tool.pdm.dev-dependencies]
tests = [
    "pytest>=7.2.1",
    "psycopg2>=2.9.6",
    "snowflake-connector-python>=3.0.4",
    "fakesnow>=0.1.0",
]
```

When I run my `pyunit` tests, I get:

```
Traceback:
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/readers/test_snowflake.py:3: in <module>
    import fakesnow
.venv/lib/python3.10/site-packages/fakesnow/__init__.py:17: in <module>
    import fakesnow.fakes as fakes
.venv/lib/python3.10/site-packages/fakesnow/fakes.py:9: in <module>
    import pandas as pd
E   ModuleNotFoundError: No module named 'pandas'
```

It looks like fakesnow is importing pandas but doesn't declare it as a dependency.

I do see that the `[pandas]` snowflake [extra_requires](https://github.com/snowflakedb/snowflake-connector-python/blob/main/setup.cfg#L97) does declare it as a dependency, but it doesn't appear to be installing from your package.

**Comment by tekumara** [comment]
Oh interesting, it looks like the pdm resolver effectively takes your `snowflake-connector-python>=3.0.4` requirement and overrides [fakesnow's dependency](https://github.com/tekumara/fakesnow/blob/v0.1.0/pyproject.toml#L13) on `snowflake-connector-python[pandas]`, and so pandas isn't installed. I haven't seen this behaviour with the pip resolver, which I'm more familiar with. I'll look into it.
