### ISSUE TITLE
Mock table

### ISSUE THREAD

**Issue by Stegallo** [tekumara/fakesnow#56]
Hello! I wonder if it is already possible to have a way to "mock" tables that we don't really have control over.

Use case is when some tables exists on a schema different from the one we are deploying in, and are referenced by our code.

For tables outside of the schema we control, it will be unpractical to provide a definition for them, so I'm envisioning being able to "mock" tables on a schema so that any query selecting on any table defined on this schema will be successful.

Example:
```
-- This will fail with Catalog Error: Table with name EXTERNAL_SCHEMA.EXAMPLE_TABLE does not exists!
CREATE VIEW EXAMPLE_VIEW AS
 SELECT COLUMN_A, COLUMN_B 
   FROM EXTERNAL_SCHEMA.EXAMPLE_TABLE
```

let's say we are able to define a mock for schema EXTERNAL_SCHEMA
```
-- This results in success
CREATE VIEW EXAMPLE_VIEW AS
 SELECT COLUMN_A, COLUMN_B 
   FROM EXTERNAL_SCHEMA.EXAMPLE_TABLE
```

**Comment by tekumara** [comment]
I think you have to create `EXTERNAL_SCHEMA.EXAMPLE_TABLE` yourself, as there's isn't enough information to know what the column types are, eg:

```sql
CREATE SCHEMA EXTERNAL_SCHEMA
CREATE TABLE  EXTERNAL_SCHEMA.EXAMPLE_TABLE (COLUMN_A int, COLUMN_B int)
```

**Comment by Stegallo** [comment]
thanks for confirming.
I'll create the schema and table explicitly for my use case
